### ISSUE TITLE
Receiving warning: CUICatalog: Invalid asset name supplied: ''

### ISSUE THREAD

**Issue by jtressle** [exyte/fan-menu#10] opened 2017-10-12 22:05 UTC
When an image string is left blank (like in the TaskViewController example), one gets the warning:

> CUICatalog: Invalid asset name supplied: ''

Easy fix is to add:

`if (!button.image.isEmpty) {...}`

around the two places an UIImage is loaded.

Thanks!

**Comment by zapletnev** [comment] 2017-10-13 04:26
Thanks for reporting @jtressle. The issue is fixed in the master branch.

**Closed** 2017-10-13 04:25 UTC

**Comment by alanjturn** [comment] 2024-07-05 17:25
how can I find the line of code in my project that is giving this error? Is there a way to do this using the console?
